Add event before login
apostrophecms/apostrophe-headless pull request #58
Opened 2020-10-28 07:26 UTC by Jose96GIT

I've added a call to apostrophe-login:before event as in the web login, so that when we add a behaviour in the event, it affects to both, web and api logins.

2020-11-03 19:05 UTC, boutell approved these changes
Good idea!

2020-11-03 19:06 UTC, boutell commented
Hmm, actually I'm a bit concerned this could go wrong. Code written for the beforeLogin event would probably assume it's OK to manipulate req.session or even redirect the user, neither of which would go well in a headless context.

I think a separate event would be a wise choice for 2.x.

2020-11-03 21:36 UTC, boutell requested changes
Should be a separate event just for headless. Which means it can use `self.emit` rather than `callAllAndEmit`.

2020-11-04 11:48 UTC, Jose96GIT commented
As I have changed the event to a separate one which exclusive for headless, I've also change the event name from `before` to `beforeLogin`. Do you agree with this name?

2020-11-05 20:02 UTC, boutell requested changes

2020-11-05 20:02 UTC, boutell commented on index.js
> +            await self.emit('beforeLogin', req);
This may throw an exception, in which case it must be caught and passed to the callback as the first argument.

2020-11-09 13:38 UTC, boutell requested changes
Looks good — would you mind adding it to the README? Also please add a semicolon after `return callback(e)` although we could clean that up on our end if you prefer.

2020-11-17 10:36 UTC, Jose96GIT commented
In addition to adding it to the README, I have also added it to the CHANGELOG.

2020-11-17 18:00 UTC, boutell approved these changes

2020-11-17 18:00 UTC, merged

2020-11-17 18:00 UTC, boutell commented
Thanks!

2020-11-17 19:09 UTC, abea commented
We're going to need to revert this. It is breaking failing several tests.